name: Build crAPI community service

on:
  pull_request:
    paths:
      - '.github/workflows/build-and-release-crapi-community.yml'
      - 'crAPI/services/community/**'
  push:
    paths:
      - '.github/workflows/build-and-release-crapi-community.yml'
      - 'crAPI/services/community/**'
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

jobs:
  build-community-image:
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'

      - name: Build image
        uses: aevea/action-kaniko@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          image: levoai/crapi-community
          path: ./crAPI/services/community
          tag: latest
          cache: true
          # Don't push the image, just build it to validate it.
          extra_args: "--no-push --cache-repo levoai/crapi-community-cache"

  push-latest-community-image:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'

      - name: Latest image push
        uses: aevea/action-kaniko@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          image: levoai/crapi-community
          path: ./crAPI/services/community
          tag: latest
          cache: true
          extra_args: "--cache-repo levoai/crapi-community-cache"

  release-community-image:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'

      - name: Tagged image push
        uses: aevea/action-kaniko@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          image: levoai/crapi-community
          path: ./crAPI/services/community
          strip_tag_prefix: v
          cache: true
          extra_args: "--cache-repo levoai/crapi-community-cache"
