name: Build and publish crapi-all image

on:
  pull_request:
    paths:
      - '.github/workflows/*-all-image.yml'
      - 'beginner-demo/**'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-docker-image:
    name: Build crapi-all Docker image
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: docker build -t levoai/crapi-all crAPI

  push-crapi-all-to-dockerhub:
    name: Publish crAPI fat image to Dockerhub
    # if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Publish
        uses: aevea/action-kaniko@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          image: levoai/crapi-all
          path: ./crAPI
          cache: true
          extra_args: "--cache-repo levoai/crapi-all-cache"
